# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: install dependencies
      run: 
        npm ci
        npm run build --if-present 
        npm test
    - name: deploy
      env: 
        HEROKU_AUTH_TOKEN: ${{secrets.HEROKU_AUTH_TOKEN}}
      run: 
        git remote add heroku https://heroku:${{HEROKU_AUTH_TOKEN}}@git.heroku.com/stormy-stream-66701.git
        git push heroku HEAD:main -f
